server:
  port: 8085
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo}
    username: ${DATASOURCE_USER:demo}
    password: ${DATASOURCE_PASSWORD:aaa}
logging:
  level:
    com.martikan.springtestdemo: debug
    org.hibernate.jpa: debug
    org.hibernate.jdbc: debug
    liquibase.database: debug
    org.springframework.web: debug